package org.tallerjava.moduloSucive.interfase.api.classes;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.2-jbossorg-4
 * 2024-05-25T18:58:51.566-03:00
 * Generated source version: 3.5.2-jbossorg-4
 *
 */
@WebService(targetNamespace = "http://soap.ws.interfaces.example00/", name = "PagoSOAP")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PagoSOAP {

    @WebMethod
    @WebResult(name = "PagoResponse", targetNamespace = "http://soap.ws.interfaces.example00/", partName = "PagoResponse")
    public PagoResponse realizarPago(

        @WebParam(partName = "matricula", name = "matricula")
        java.lang.String matricula,
        @WebParam(partName = "monto", name = "monto")
        int monto
    );
}
